services:
  - type: web
    name: tiktok-pro-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        fromService:
          type: web
          name: tiktok-pro-downloader
          property: port